name: Daily Sports Update

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 時間 01:00 執行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 移除安裝步驟，無 package.json 不需要
    # - name: Install dependencies
    #   run: npm install

    - name: Run update script
      run: node scripts/fetch_scores.js

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add index.html
        git status
        git diff --cached
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update scores $(date +'%Y-%m-%d')"
          git push origin HEAD:main --force
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
