- name: Commit and push changes
  run: |
    set -x  # 打開執行指令回顯，方便看詳細執行流程

    git config user.name "github-actions"
    git config user.email "actions@github.com"

    echo "本地分支狀態:"
    git branch -a

    echo "遠端分支狀態:"
    git ls-remote

    echo "fetch 遠端 main 分支"
    git fetch origin main

    echo "強制切換本地 main 分支指向遠端 main"
    git checkout -B main origin/main

    git add index.html
    git status
    git diff --cached

    if git diff --cached --quiet; then
      echo "無需提交的變更"
    else
      git commit -m "更新賽事 $(date +'%Y-%m-%d')"
      echo "推送更新到遠端 main"
      git push origin main --force
    fi
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
